# Identifiants de ton projet sur SonarCloud
sonar.organization=ahahlban
sonar.projectKey=Ahahlban_projet-ecole-bourse

# Dossier à analyser (le '.' signifie le dossier courant)
sonar.sources=.

# Exclure les fichiers qui ne sont pas de ton code (tests, environnement virtuel, etc.)
sonar.exclusions=venv/**, tests/**, .github/**

# Préciser que c'est un projet Python
sonar.language=py
sonar.python.version=3.12