# Identifiants de ton projet sur SonarCloud
sonar.organization=ahahlban
sonar.projectKey=Ahahlban_projet-ecole-bourse

# Dossier à analyser (le '.' signifie le dossier courant)
sonar.sources=.

# Exclure les fichiers qui ne sont pas de ton code (tests, environnement virtuel, etc.)
sonar.exclusions=venv/**, tests/**, .github/**

# Rapport de couverture genere par pytest-cov dans GitHub Actions
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=main.py,modules/dashboard.py,modules/export.py,modules/school_search.py,modules/student_guidance.py

# Préciser que c'est un projet Python
sonar.language=py
sonar.python.version=3.12
