name: SonarCloud Analysis

on:
  push:
    branches:
      - main # S'assure que l'analyse se lance quand tu pousses sur le main
  pull_request:
    types: [opened, synchronize, reopened] # L'analyse se lancera aussi sur tes Pull Requests

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          # Très important : Sonar a besoin de l'historique complet pour comprendre ce qui est "nouveau"
          fetch-depth: 0  

      - name: Lancer l'analyse SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ce token est géré automatiquement par GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # C'est le secret que tu as ajouté à l'étape 1